const fs = require('fs');
const path = require('path');

function detectTechStack(dir) {
  const detected = [];
  const exists = (f) => fs.existsSync(path.join(dir, f));

  if (exists('build.gradle') || exists('build.gradle.kts')) {
    if (exists('app/src/main/AndroidManifest.xml') || exists('AndroidManifest.xml')) {
      detected.push({ id: 'android', name: 'Android', detail: 'Kotlin/Java (Gradle)', buildFile: 'build.gradle.kts' });
    } else {
      detected.push({ id: 'jvm', name: 'JVM', detail: 'Kotlin/Java (Gradle)', buildFile: 'build.gradle.kts' });
    }
  }

  if (exists('Podfile') || exists('Package.swift')) {
    const entries = fs.readdirSync(dir);
    const workspace = entries.find(f => f.endsWith('.xcworkspace') || f.endsWith('.xcodeproj'));
    detected.push({ id: 'ios', name: 'iOS', detail: `Swift/ObjC${workspace ? ` (${workspace})` : ''}` });
  }

  if (exists('package.json') && !exists('build.gradle') && !exists('build.gradle.kts')) {
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
    const isTS = exists('tsconfig.json');
    const framework = pkg.dependencies?.next ? 'Next.js' :
                      pkg.dependencies?.react ? 'React' :
                      pkg.dependencies?.express ? 'Express' :
                      pkg.dependencies?.fastify ? 'Fastify' : 'Node.js';
    detected.push({ id: 'node', name: isTS ? 'TypeScript' : 'JavaScript', detail: framework });
  }

  if (exists('pyproject.toml') || exists('requirements.txt') || exists('setup.py') || exists('Pipfile')) {
    const framework = exists('manage.py') ? 'Django' :
                      exists('app/main.py') ? 'FastAPI' : 'Python';
    detected.push({ id: 'python', name: 'Python', detail: framework });
  }

  if (exists('Gemfile')) {
    const isRails = exists('config/routes.rb');
    detected.push({ id: 'ruby', name: 'Ruby', detail: isRails ? 'Rails' : 'Ruby' });
  }

  if (exists('go.mod')) {
    detected.push({ id: 'go', name: 'Go', detail: 'Go modules' });
  }

  if (exists('Cargo.toml')) {
    detected.push({ id: 'rust', name: 'Rust', detail: 'Cargo' });
  }

  const dirEntries = fs.readdirSync(dir);
  if (dirEntries.some(f => f.endsWith('.csproj') || f.endsWith('.sln'))) {
    detected.push({ id: 'dotnet', name: '.NET', detail: 'C#' });
  }

  return detected;
}

function generateProjectConfig(dir, stack) {
  const stackIds = stack.map(s => s.id);
  const techNames = stack.map(s => `${s.name} (${s.detail})`).join(', ') || 'generic';

  let coverage = 80;
  let linter = 'eslint';
  let testFramework = 'jest';
  let extras = '';

  if (stackIds.includes('android')) {
    coverage = 80;
    linter = 'ktlint + detekt';
    testFramework = 'JUnit5 + Espresso';
    extras = `
android:
  min_sdk: 26
  target_sdk: 34
  backward_compatibility_months: 18
  newrelic_sdk: true
  proguard: true`;
  } else if (stackIds.includes('ios')) {
    coverage = 80;
    linter = 'swiftlint';
    testFramework = 'XCTest';
    extras = `
ios:
  min_deployment_target: "15.0"
  backward_compatibility_months: 18
  cocoapods: true`;
  } else if (stackIds.includes('python')) {
    coverage = 95;
    linter = 'ruff + mypy';
    testFramework = 'pytest';
  } else if (stackIds.includes('node')) {
    coverage = 90;
    linter = 'eslint + prettier';
    testFramework = 'jest / vitest';
  } else if (stackIds.includes('go')) {
    coverage = 80;
    linter = 'golangci-lint';
    testFramework = 'go test';
  } else if (stackIds.includes('rust')) {
    coverage = 80;
    linter = 'clippy';
    testFramework = 'cargo test';
  }

  const config = `# Auto-generated by Agentic SDLC Framework v1.0
# Detected stack: ${techNames}

project:
  name: "${path.basename(dir)}"
  tech_stack: "${techNames}"

quality_gates:
  coverage_threshold: ${coverage}
  test_pass_rate: 100
  lint_errors: 0
  linter: "${linter}"
  test_framework: "${testFramework}"
  pr_review_required: true
  min_reviewers: 1

bounded_context:
  now_md_max_tokens: 200
  history_rotation: true
  max_protocol_load: 3
${extras}
`;

  const configPath = path.join(dir, '.ai', 'project-config.yaml');
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(configPath, config);
  return config;
}

function copyDirRecursive(src, dest) {
  const normalizedSrc = src.split(path.sep).join('/');
  if (normalizedSrc.includes('/.ai/session-state')) {
    return;
  }

  fs.mkdirSync(dest, { recursive: true });
  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.name === 'registry.json' && normalizedSrc.endsWith('/.ai/plugins')) {
      continue;
    }

    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function validateKnowledgeGraph(kg) {
  const errors = [];

  if (!kg.meta) errors.push('Missing meta section');
  if (!kg.nodes || !Array.isArray(kg.nodes)) errors.push('Missing or invalid nodes array');
  if (!kg.edges || !Array.isArray(kg.edges)) errors.push('Missing or invalid edges array');
  if (!kg.groups || typeof kg.groups !== 'object') errors.push('Missing or invalid groups object');

  if (kg.nodes) {
    const nodeIds = new Set();
    for (const node of kg.nodes) {
      if (!node.id) errors.push(`Node missing id: ${JSON.stringify(node)}`);
      if (!node.name) errors.push(`Node ${node.id} missing name`);
      if (!node.group) errors.push(`Node ${node.id} missing group`);
      if (nodeIds.has(node.id)) errors.push(`Duplicate node id: ${node.id}`);
      nodeIds.add(node.id);

      if (node.group && kg.groups && !kg.groups[node.group]) {
        errors.push(`Node ${node.id} references unknown group: ${node.group}`);
      }

      const validRisks = ['low', 'med', 'high', 'critical'];
      if (node.risk && !validRisks.includes(node.risk)) {
        errors.push(`Node ${node.id} has invalid risk level: ${node.risk}`);
      }
    }

    if (kg.edges) {
      for (const edge of kg.edges) {
        if (!edge.source) errors.push('Edge missing source');
        if (!edge.target) errors.push('Edge missing target');
        if (edge.source && !nodeIds.has(edge.source)) {
          errors.push(`Edge references unknown source node: ${edge.source}`);
        }
        if (edge.target && !nodeIds.has(edge.target)) {
          errors.push(`Edge references unknown target node: ${edge.target}`);
        }
      }
    }
  }

  return { valid: errors.length === 0, errors };
}

function aggregateScanResults(scanResults, kg) {
  const REPO_TO_NODE_ID = {
    'mobile-ios-app': 'mobile-ios-app',
    'companion-ios-app': 'companion-ios-app',
    'mobile-android-app': 'mobile-android-app',
    'shared-mobile-sdk': 'shared-mobile-sdk',
    'mobile-telemetry-sdk': 'mobile-telemetry-sdk',
    'api-gateway': 'api-gateway',
    'design-service': 'design-service',
    'analytics-web': 'analytics-web',
    'admin-console': 'admin-console',
    'customer-portal': 'customer-portal',
    'workflow-studio-web': 'workflow-studio-web',
    'config-studio': 'config-studio',
    'account-directory': 'account-directory',
    'account-directory-service': 'account-directory',
    'preferences-web': 'preferences-web',
    'preferences-service': 'preferences-web',
    'localization-service': 'localization-service',
    'rules-engine-service': 'rules-engine-service',
    'feature-config-service': 'feature-config-service',
    'orchestration-service': 'orchestration-service',
  };

  let totalFindings = 0;
  const highCritRepos = [];

  for (const scan of scanResults) {
    const nodeId = REPO_TO_NODE_ID[scan.repo] || scan.repo;
    const node = kg.nodes.find(n => n.id === nodeId);

    if (!node) continue;

    node.scan = {
      scanned_at: scan.scanned_at,
      stack: scan.stack,
      vulnerabilities: scan.vulnerabilities,
      outdated_packages: scan.outdated_packages,
      secrets_detected: scan.secrets_detected,
      license_issues: scan.license_issues,
    };

    const v = scan.vulnerabilities || {};

    if (scan.risk === 'critical' || scan.risk === 'high') {
      if (node.risk !== 'high') node.risk = 'high';
      highCritRepos.push(scan.repo);
    } else if (scan.risk === 'med' && node.risk === 'low') {
      node.risk = 'med';
    }

    totalFindings += (v.total || 0) + (scan.secrets_detected || 0);
  }

  return { totalFindings, highCritRepos };
}

module.exports = {
  detectTechStack,
  generateProjectConfig,
  copyDirRecursive,
  validateKnowledgeGraph,
  aggregateScanResults,
};
